# Generated by Django 5.2.7 on 2025-10-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_branch_itemtype_patron_categories_delete_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_code', on_delete=django.db.models.deletion.PROTECT, related_name='patrons', to='myapp.patron_categories')),
            ],
            options={
                'verbose_name': 'patron',
                'verbose_name_plural': 'patrons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
