# Generated by Django 5.2.7 on 2025-10-17 19:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_biblio_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_days', models.PositiveIntegerField(help_text='How many days per loan.', validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('renewal_allowed', models.BooleanField(default=True)),
                ('max_renewals', models.PositiveIntegerField(default=2)),
                ('item_type', models.ForeignKey(db_column='item_type', on_delete=django.db.models.deletion.CASCADE, related_name='issuing_rules', to='myapp.itemtype')),
                ('patron_category', models.ForeignKey(db_column='patron_category', on_delete=django.db.models.deletion.CASCADE, related_name='issuing_rules', to='myapp.patron_categories')),
            ],
            options={
                'verbose_name': 'issuing rule',
                'verbose_name_plural': 'issuing rules',
                'ordering': ['patron_category__code', 'item_type__code'],
                'unique_together': {('patron_category', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='myapp.item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='myapp.patron')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['patron', 'due_at'], name='myapp_loan_patron__37adf8_idx'), models.Index(fields=['item', 'due_at'], name='myapp_loan_item_id_cbf4b3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('return_date__isnull', True)), fields=('item',), name='unique_active_loan_per_item')],
            },
        ),
    ]
