# Generated by Django 5.2.7 on 2025-10-17 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_issuingrule_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(default='OVERDUE', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='myapp.item')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='myapp.loan')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='myapp.patron')),
            ],
            options={
                'indexes': [models.Index(fields=['patron'], name='myapp_fine_patron__cb7543_idx'), models.Index(fields=['loan'], name='myapp_fine_loan_id_c82a85_idx'), models.Index(fields=['item'], name='myapp_fine_item_id_a3b1bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('loan', 'fine_type'), name='unique_overdue_fine_per_loan')],
            },
        ),
    ]
